### PR TITLE
RELATED: PMK-201 GD.UI Demo - Building Custom Visualizations

### PR DESCRIPTION
**Pull request by BugsBunny338**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Review by twgonzalez — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/156/ : SUCCESS in 9m 35s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-demo-merge-compliance-check/9/ : SUCCESS in 17s

**Pull request merged**
